apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: sperigpt4-base

resources:
  - namespace.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - ingress.yaml
  - certificate.yaml

commonLabels:
  app: sperigpt4
  tenant: opsera
  managed-by: argocd
