# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  ROLLOUTS KUSTOMIZATION                                                       ║
# ║  sperigpt-01 - Code-to-Cloud v0.6 - Powered by Opsera                        ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - analysis-template-http.yaml
