apiVersion: v1
kind: ConfigMap
metadata:
  name: sperichatgpt2-config
  labels:
    app: sperichatgpt2
data:
  ENVIRONMENT: "dev"
  LOG_LEVEL: "INFO"
  BACKEND_URL: "http://sperichatgpt2-backend:8000"
