apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opseratest-sperichatgpt2-dev

resources:
  - ../../base

commonLabels:
  environment: dev
  tenant: opseratest

images:
  - name: sperichatgpt2-backend
    newName: 792373136340.dkr.ecr.us-east-1.amazonaws.com/opseratest/sperichatgpt2-backend
    newTag: 4e92b19-20260130183508
  - name: sperichatgpt2-frontend
    newName: 792373136340.dkr.ecr.us-east-1.amazonaws.com/opseratest/sperichatgpt2-frontend
    newTag: 4e92b19-20260130183508

patches:
  # Patch ingress for dev environment
  - target:
      kind: Ingress
      name: sperichatgpt2
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: opseratest-sperichatgpt2-dev.agent.opsera.dev
      - op: replace
        path: /spec/tls/0/hosts/0
        value: opseratest-sperichatgpt2-dev.agent.opsera.dev
      - op: replace
        path: /spec/tls/0/secretName
        value: opseratest-sperichatgpt2-dev-tls

  # Scale down for dev
  - target:
      kind: Deployment
      name: sperichatgpt2-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: sperichatgpt2-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
