apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-sperigpt4-dev

resources:
  - ../../base

commonLabels:
  environment: dev

# Images will be updated by CI/CD workflow
images:
  - name: sperigpt4-frontend
    newName: PLACEHOLDER_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/opsera/sperigpt4-frontend
    newTag: latest
  - name: sperigpt4-backend
    newName: PLACEHOLDER_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/opsera/sperigpt4-backend
    newTag: latest

# Patches for dev environment
patches:
  - target:
      kind: Deployment
      name: sperigpt4-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: sperigpt4-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
