# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  NAMESPACE - QA Environment                                                   ║
# ║  sperigpt-01 - Code-to-Cloud v0.6 - Powered by Opsera                        ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

apiVersion: v1
kind: Namespace
metadata:
  name: sperigpt-01-qa
  labels:
    environment: qa
    app.kubernetes.io/part-of: sperigpt-01
