apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-chatgptsperi6-dev

resources:
  - ../../base

commonLabels:
  environment: dev

# Images will be updated by CI/CD pipeline
images:
  - name: chatgptsperi6-frontend
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/chatgptsperi6-frontend
    newTag: d005b97-20260131121342
  - name: chatgptsperi6-backend
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/chatgptsperi6-backend
    newTag: d005b97-20260131121342

# Replica count for DEV environment
replicas:
  - name: chatgptsperi6-frontend
    count: 2
  - name: chatgptsperi6-backend
    count: 2
