apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-chatgptsperi6-dev

resources:
  - ../../base

labels:
  - pairs:
      environment: dev
    includeSelectors: false

# Images will be updated by CI/CD pipeline
images:
  - name: chatgptsperi6-frontend
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/chatgptsperi6-frontend
    newTag: 4d8f9b1-20260131122738
  - name: chatgptsperi6-backend
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/chatgptsperi6-backend
    newTag: 4d8f9b1-20260131122738

# Replica count for DEV environment
replicas:
  - name: chatgptsperi6-frontend
    count: 2
  - name: chatgptsperi6-backend
    count: 2
